#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 25 07:03:02 2021

@author: camilasaldivar
"""
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.stats import norm


diabetes = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/AHI_DataSci_507/main/Datasets/Diabetes/DB1_Diabetes/diabetic_data.csv')

timeinhospital = diabetes['time_in_hospital']
labprocedures = diabetes['num_lab_procedures'] 
gender = diabetes['gender']



from scipy.stats import shapiro
import scipy.stats as stats
from matplotlib import pyplot
from scipy.stats import ttest_ind

diabetes_small = diabetes.sample(100)

timeinhospital = diabetes['time_in_hospital']
labprocedures = diabetes['num_lab_procedures'] 


##Total count of procedures

diabetes['totalCountProcedures'] = diabetes['num_procedures'] + diabetes['num_lab_procedures']
diabetes['totalCountProcedures'].describe()
totalCountProcedures = diabetes['totalCountProcedures'].array


###T-Test

### Difference between number of lab procedures and gender
Female['totalCountProcedures'] = Female['num_procedures'] + Female['num_lab_procedures']
Male['totalCountProcedures'] = Male['num_procedures'] + Male['num_lab_procedures']


Female = diabetes[diabetes['gender']=='Female']
Male = diabetes[diabetes['gender']=='Male']
ttest_ind(Female['totalCountProcedures'], Male['totalCountProcedures'])
#####   statistic=-0.6747218803792331, pvalue=0.4998540133474586

## There is no difference in average number of procedures between males and females 
##because the p-value is greater than 0.05, which means that we fail to reject the null hypothesis 


#### difference between gender (M:F) and the number of days in hospital

ttest_ind (Female['time_in_hospital'], Male['time_in_hospital'])
#### statistic=9.542637042242887, pvalue=1.4217299655114968e-21

## There is a significant difference in time in hospital between males and females 
## because the p-value is less than 0.05, which allows us to reject the null hypothesis 

#####difference between RACE (Caucasian and African American) and the number of days in hospital
Caucasian = diabetes[diabetes['race']=='Caucasian']
AfricanAmerican = diabetes[diabetes['race']=='AfricanAmerican']
ttest_ind(Caucasian['time_in_hospital'], AfricanAmerican['time_in_hospital'])
####Result    statistic= -5.0610017032095325, pvalue=4.178330085585203e-07)

# There is a significant difference in time in hospital between Caucasians and African Americans
## because the p-value is less than 0.05, which allows us to reject the null hypothesis 

###difference between RACE (Asian and African American) and  Number of lab procedures 

Asian = diabetes[diabetes['race']=='Asian']
AfricanAmerican = diabetes[diabetes['race']=='AfricanAmerican']


ttest_ind(Asian['totalCountProcedures'], AfricanAmerican['totalCountProcedures'])
####Result  Ttest_indResult(statistic=-3.7897663070631253, pvalue=0.00015123463923369748)

##There is a significant difference in number of lab procedures between Asians and African Americans
## because the p-value is less than 0.05, which allows us to reject the null hypothesis 
